services:
  postgres:
    image: debezium/example-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'