jsonplace:
  url: https://jsonplaceholder.typicode.com
spring:
  threads:
    virtual:
      enabled: true
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:postgresql://localhost:5432/postgres
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
  #r2dbc:
  #  username: root
  #  password: root
  #  url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: transaction-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0