jsonplace:
  url: https://jsonplaceholder.typicode.com
spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: client1
            client-secret: my-secret
            authorization-grant-type: authorization_code
            scope: message.read,message.write
        provider:
          spring:
            issuer-uri: http://localhost:9000
  thread-executor: virtual
  threads:
    virtual:
      enabled: true
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: jdbc:postgresql://localhost:5432/postgres
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
  #r2dbc:
  #  username: root
  #  password: root
  #  url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: transaction-service
  kafka:
    bootstrap-servers:
      - localhost:9093

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

monday: Mon-Day!
tuesday: TuesDAY#
wednesday: Wednes@day
thursday: THURSday^
friday: Fri:Day_%
saturday: Satur_DAY
sunday: Sun+Day